version: '3'
services:
  frontend:
    build: ./frontend/
    ports: ['8080:8080']
    environment: 
      BACKEND_PORT: 9000
      BACKEND_DNS: backend
  backend:
    build: ./backend/
    ports: ['9000:9000']  