apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend 
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z database 6379; do sleep 1; done;']
      containers:
      - name: backend
        image: ghcr.io/frejastrand/backend-fortune-app:latest
        ports:
        - containerPort: 9000
        env:
            - name: REDIS_DNS 
              value: 'database'