apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend 
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/frejastrand/backend-fortune-app:latest
        ports:
        - containerPort: 9000