name: Go Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [emil,freja,gustav]
env:
  docker_username: frejastrand
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt update

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Install GCC
        run: sudo apt install -y gcc

      - name: Run test finally
        working-directory: frontend
        run: go test

  store_artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload code
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: . 
  
  Docker_image: 
    runs-on: ubuntu-22.04
    needs: [store_artifact]
    permissions:
      packages: write
    steps:
      - name: download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: build frontend docker
        run: chmod +x ./build-frontend-docker.sh && ./build-frontend-docker.sh
      - name: build backend docker
        run: chmod +x ./build-backend-docker.sh && ./build-backend-docker.sh
      - name: push frontend docker
        run: chmod +x ./push-frontend-docker.sh && ./push-frontend-docker.sh
      - name: push backend docker
        run: chmod +x ./push-backend-docker.sh && ./push-backend-docker.sh

  k8s-deploy:
      name: Deploy
      needs: [Docker_image]
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions-hub/kubectl@master
          with:
            args: get pods