name: Go Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [emil,freja,gustav]
    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt update

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Install GCC
        run: sudo apt install -y gcc

      - name: Run test finally
        working-directory: frontend
        run: go test